---
- name: "Server initialization"
  hosts: remoteserver
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
    - name: If the (.env.ansible) file does not exist, FAIL
      debug: msg="{{ lookup('file', "../.env.ansible", errors='strict') }}"
      no_log: true

    - name: APT | Update & Upgrade
      apt:
        update_cache: yes
        upgrade: yes

    - name: "Install packages"
      apt:
        name:
          - unzip
        state: latest

    - name: Install python-ldap python package
      pip:
        name: python-ldap

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: latest

    - name: NPM | Install PM2
      npm:
        name: pm2
        global: yes
        state: present

    - name: Project directory
      set_fact:
        project_dir: /home/{{ ansible_user }}/iredmail-synchronizer

    - name: Create iredmail-synchronizer folder
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"

    - name: Unzip file
      unarchive:
        src: "../repository.zip"
        dest: "{{ project_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Install dependencies
      npm:
        path: "{{ project_dir }}"
        state: present

    - name: Copy the dotenv file
      copy:
        src: "../.env.ansible"
        dest: "{{ project_dir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        force: yes
        mode: "0644"

    - name: Build assets
      command: npm run tsc
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: true

    - name: Git clone iRedMail repository
      git:
        repo: "https://github.com/iredmail/iRedMail.git"
        dest: "{{ project_dir }}/iredmail"
        clone: yes
        update: no

    - name: Delete old pm2 process
      command: pm2 delete iredmail-ldap-Synchronizer
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: true

    - name: Start the server
      command: pm2 start dist/main.js --name iredmail-ldap-Synchronizer
      args:
        chdir: "{{ project_dir }}"

    - name: CRON | PM2 iredmail-ldap-Synchronizer restart
      cron:
        name: pm2 restart iredmail-ldap-Synchronizer
        special_time: daily
        job: "pm2 restart iredmail-ldap-Synchronizer"

    - name: Pm2 synchronize
      command: pm2 save
      args:
        chdir: "{{ project_dir }}"
